<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTXxlgu3\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTXxlgu3/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTXxlgu3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTXxlgu3\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerTXxlgu3\srcApp_KernelProdContainer([
    'container.build_hash' => 'TXxlgu3',
    'container.build_id' => '21332e5b',
    'container.build_time' => 1585923164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTXxlgu3');
