<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'sextans_api' => [[], ['_controller' => 'App\\Controller\\SextansApiController::index'], [], [['text', '/']], [], []],
    'show_users_api' => [[], ['_controller' => 'App\\Controller\\SextansApiController::ShowAllUsersAction'], [], [['text', '/api/v1/show-users/']], [], []],
    'save_user_api' => [[], ['_controller' => 'App\\Controller\\SextansApiController::saveSingleUserAction'], [], [['text', '/api/v1/save-user/']], [], []],
];
