<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZOdt5qr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZOdt5qr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZOdt5qr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZOdt5qr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZOdt5qr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZOdt5qr',
    'container.build_id' => '66b2ca85',
    'container.build_time' => 1585923172,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZOdt5qr');
